name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=SnakeGame --add-data="*.py;." snake_game.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-windows
        path: dist/snake_game.exe

    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/snake_game.exe
        asset_name: snake-game-windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload to latest release
      if: github.event_name != 'release'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: dist/snake_game.exe
        name: Latest Build
        body: Automatically generated build from latest commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}